# Application URLs
base.url=https://www.saucedemo.com/

# User Credentials
username.problem=problem_user
password.default=secret_sauce

# Timeouts
wait.timeout.default=10
social.media.redirect.timeout=10
social.media.window.switch.timeout=5